* KVFinder web service

[[GitHub Release][https://img.shields.io/github/v/release/LBC-LNBio/KVFinder-web-service.svg?color=informational]]
[[https://opensource.org/licenses/Apache-2.0][https://img.shields.io/badge/License-Apache%202.0-blue.svg]]
# [[GitHub Release](https://img.shields.io/github/v/release/LBC-LNBio/KVFinder-web-service.svg?color=informational)
# [![L](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)
# <!-- [![DOI](http://joss.theoj.org/papers)](http://joss.theoj.org/papers) -->

Welcome to the KVFinder-web service, this page was built to help you get started with our web service.

KVFinder-web service is a RESTful web service that runs [[parKVFinder][https://github.com/LBC-LNBio/parKVFinder]] software to detect and chacterize cavities. KVFinder-web service has three modules: web, queue and worker. Each one runs in single docker containers, but they are combined into a docker-compose configuration file.

** Publicly available KVFinder-web service

We provide a publicly available KVFinder-web service (http://parkvfinder.cnpem.br), running in a Cloud environment, that has some limitations compared to parKVFinder local installation, which are stated on the [[documentation][https://lbc-lnbio.github.io/KVFinder-web]]. Hence, users may opt to run jobs on our public KVFinder-web service or on a locally configured server.

** Local install

To run this web service in linux distributions it is necessary to install docker-compose and its dependencies. In Debian/Ubuntu and derivatives, execute:

#+begin_example
$ sudo apt install docker-compose
#+end_example

After the docker-compose installation and copy/clone of this repository. To start KVFinder-web service, you can execute the command bellow at the root  of KVFinder-web-service repository (where docker-compose.yml file is located):

#+begin_src
$ docker-compose up
#+end_src

To start the KVFinder-web service in background:

#+begin_src
$ docker-compose up -d
#+end_src

To interrupt an active KVFinder-web service instance, run:

#+begin_src
$ docker-compose down
#+end_src

To stop and erase the volumes that store the queue module data and the job folders and files, run:

#+begin_src
$ docker-compose down --volumes
#+end_src

The KVFinder-web service uses port 8081 by default. If the local installation was successfully, the link bellow should present a text message like: "KVFinder Web". You can use a browser to test.

[[http://localhost:8081][http://localhost:8081]]

Job queue information can be accessed at:

[[http://localhost:8023/info][http://localhost:8023/info]]

*** Extra configuration

After changes in the source code, the containers must be rebuild.

#+begin_src
$ docker-compose build
#+end_src

or

#+begin_src
$ docker-compose up --build
#+end_src

To start more than one worker module and thus make KVFinder-web service capable of running more than one job simultaneously. For instance, to start with two worker modules:

#+begin_src
$ docker-compose up --scale kv-worker=2
#+end_src

** API

*** Create a job

*POST /create*

- URL: [[http://localthost:8081/create][http://localhost:8081/create]]
- Method: POST
- Media type: 'application/json'

Example of job request:

#+begin_src json
{
  "pdb": [
    "MODEL        1\n",
    "ATOM      1  N   GLU E  13      -6.693 -15.642 -14.858  1.00100.00           N  \n",
    (...)
   "END\n"
  ],
  "settings": {
    "modes": {
      "whole_protein_mode": true,
      "box_mode": false,
      "resolution_mode": "Low",
      "surface_mode": true,
      "kvp_mode": false,
      "ligand_mode": false
    },
    "step_size": {
      "step_size": 0.0
    },
    "probes": {
      "probe_in": 1.4,
      "probe_out": 4.0
    },
    "cutoffs": {
      "volume_cutoff": 5.0,
      "ligand_cutoff": 5.0,
      "removal_distance": 0.0
    },
    "visiblebox": {
      "p1": { "x": 0.0, "y": 0.0, "z": 0.0 },
      "p2": { "x": 0.0, "y": 0.0, "z": 0.0 },
      "p3": { "x": 0.0, "y": 0.0, "z": 0.0 },
      "p4": { "x": 0.0, "y": 0.0, "z": 0.0 }
    },
    "internalbox": {
      "p1": { "x": -4.0, "y": -4.0, "z": -4.0 },
      "p2": { "x": 4.0, "y": -4.0, "z": -4.0 },
      "p3": { "x": -4.0, "y": 4.0, "z": -4.0 },
      "p4": { "x": -4.0, "y": -4.0, "z": 4.0 }
    }
  }
}
#+end_src


*** Request a result

*GET /:id*

- URL: [[http://localhost:8081/:id][http://localhost:8081/:id]]
- Method: GET

Where *:id*  is the job id received from the server as submission response.

Example of response obtained for a job with status "completed".

#+begin_src json
{
  "id": "17275205978013541183",
  "status": "completed",
  "output": {
    "pdb_kv": "ATOM      1  HS  KAA   259     -15.000 -10.200   0.000  1.00  0.00\nATOM      2(...)",
    "report": "# TOML results file for parKVFinder software\n\ntitle = \"parKVFinder results f(...)",
    "log": "==========\tSTART\tRUN\t=========\n\nDate and time: Fri Apr 16 11:40:06 2021\n\nRu(...)",
  },
  "created_at": "2021-04-16T11:40:02.514045822Z",
  "started_at": "2021-04-16T11:40:06.671064517Z",
  "ended_at": "2021-04-16T11:40:17.701426882Z",
  "expires_after": "1day"
}
#+end_src


** Client

In this repository, we provide a simple Python client (~client/client.py~) to interact with KVFinder-web service by requests package.

However, the recommended client is a PyMOL plugin, named PyMOL KVFinder-web Tools, that integrates KVFinder-web service with PyMOL. For more information, refer to the PyMOL KVFinder-web Tools [[repository][https://github.com/LBC-LNBio/PyMOL-KVFinder-web-tools]].

By default the PyMOL KVFinder-web Tools, users is configured to our publicly available KVFinder-web service. If users wish to use it with a locally configured server, users must change the server url hardcoded on the ~__init__.py~ file and reinstall the client plugin on PyMOL.

From:

#+begin_src python
# Server                                 
server = "http://parkvfinder.cnpem.br"   
# Port 
port = "8081" 
#+end_src

to:

#+begin_src python
# Server                                 
server = "http://localhost"              
# Port 
port = "8081" 
#+end_src

Note that if the KVFinder-web service is on another computer on your network, you must provide the IP Address instead of localhost.

** Documentation

Documentation are available at https://lbc-lnbio.github.io/KVFinder-web.

** License

The software is licensed under the terms of the Apache-2.0 License and is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the Apache-2.0 License for more details.

---
