* KVFinder web service

** Instalação local

O KVFinder-web-service é formado por três módulos. O módulo web, o módulo de fila e o módulo de execução. Cada módulo é executado em um container (docker) separado e integrados utilizando o docker-compose.

Logo, para executar o kvfinder-web-service é necessário ter instalado o docker-compose. Em distribuições derivadas do Debian e Ubuntu, o comando para instalá-lo será:

#+begin_example
$ sudo apt install docker-compose
#+end_example

O kvfinder-web-service é iniciado utilizando o comando abaixo na raiz do diretório desse repositório (onde está localizado o arquivo docker-compose.yml).

#+begin_src
$ docker-compose up
#+end_src

ou 

#+begin_src
$ docker-compose up -d
#+end_src

para executar em segundo plano.

Os comandos abaixo interrompem a execução do kvfinder-web-service.

#+begin_src
$ docker-compose down
#+end_src

ou 

#+begin_src
$ docker-compose down --volumes
#+end_src

para destruir os "volumes" que armazem os dados das filas e as pastas com os arquivos dos /jobs/.

O web service estará acessível em:

[[http://localhost:8081][http://localhost:8081]]

Informações da fila de /jobs/ poderão ser visualizadas em:

[[http://localhost:8081/info][http://localhost:8081/info]]

** API

*** Criar um job

*POST /create*

- URL: [[http://localthost:8081/create][http://localhost:8081/create]]
- Método: POST
- Media type: 'application/json'

Exemplo do json de submissão:

#+begin_src json
{
  "pdb": [
    "MODEL        1\n",
    "ATOM      1  N   GLU E  13      -6.693 -15.642 -14.858  1.00100.00           N  \n",
    (...)
   "END\n"
  ],
  "settings": {
    "modes": {
      "whole_protein_mode": true,
      "box_mode": false,
      "resolution_mode": "Low",
      "surface_mode": true,
      "kvp_mode": false,
      "ligand_mode": false
    },
    "step_size": {
      "step_size": 0.0
    },
    "probes": {
      "probe_in": 1.4,
      "probe_out": 4.0
    },
    "cutoffs": {
      "volume_cutoff": 5.0,
      "ligand_cutoff": 5.0,
      "removal_distance": 0.0
    },
    "visiblebox": {
      "p1": { "x": 0.0, "y": 0.0, "z": 0.0 },
      "p2": { "x": 0.0, "y": 0.0, "z": 0.0 },
      "p3": { "x": 0.0, "y": 0.0, "z": 0.0 },
      "p4": { "x": 0.0, "y": 0.0, "z": 0.0 }
    },
    "internalbox": {
      "p1": { "x": -4.0, "y": -4.0, "z": -4.0 },
      "p2": { "x": 4.0, "y": -4.0, "z": -4.0 },
      "p3": { "x": -4.0, "y": 4.0, "z": -4.0 },
      "p4": { "x": -4.0, "y": -4.0, "z": 4.0 }
    }
  }
}
#+end_src


*** Solicitar os resultados de um job

*GET /:id*

- URL: [[http://localhost:8081/:id][http://localhost:8081/:id]]
- Método: GET

Onde *:id* é o id recebido após a submissão do /job/.

Exemplo de json de resposta após o /job/ ter sido executado com sucesso

#+begin_src json
{
  "id": "17275205978013541183",
  "status": "completed",
  "output": {
    "pdb_kv": "ATOM      1  HS  KAA   259     -15.000 -10.200   0.000  1.00  0.00\nATOM      2(...)",
    "report": "# TOML results file for parKVFinder software\n\ntitle = \"parKVFinder results f(...)",
    "log": "==========\tSTART\tRUN\t=========\n\nDate and time: Fri Apr 16 11:40:06 2021\n\nRu(...)",
  },
  "created_at": "2021-04-16T11:40:02.514045822Z",
  "started_at": "2021-04-16T11:40:06.671064517Z",
  "ended_at": "2021-04-16T11:40:17.701426882Z",
  "expires_after": "1day"
}
#+end_src

*** Recuperar um input

*GET /retrieve-input/:id*

- URL: [[http://localhost:8081/retrieve-input/:id][http://localhost:8081/retrieve-input/:id]]
- Method: GET

Onde *:id* é o id recebido após a submissão do /job/.

Exemplo de resposta:

#+begin_src json
{
  "id": "17275205978013541183",
  "input": {
    "pdb": "ATOM   25  OD1 ASP E 323       0.497  12.598  16.506  1.00 40.80           O  \nATOM      26(...)",
    "pdb_ligand": null,
    "settings": {"probes": (...)},
  },
  "created_at": "2022-01-25T19:32:13.572099997Z",
}
#+end_src


# ** Cliente integrado ao PyMOL: PyMOL KVFinder-web Tools

# O cliente PyMOL KVFinder-web Tools está disponível em `client/PyMOL-KVFinder-web-Tools`.

# Para mais informações, use o guia disponível [aqui](https://github.com/jvsguerra/kvfinder-ws/blob/master/client/PyMOL-KVFinder-web-tools/README.md)


# ** Configurações



** Observações

Após alterações no códigos-fonte o sistema precisa ser recompilado com 

#+begin_src
$ docker-compose up --build
#+end_src

Para iniciar mais de um /worker/ e assim tornar o sistema capaz de executar
mais de 1 /job/ simultaneamente.

#+begin_src
$ docker-compose up --scale kv-worker=2
#+end_src

# Por ainda ser um sistema em fase de testes o tempo de /timeout/ de um /job/ está em *12 minutos* e o tempo que esse /job/ permanece disponível ("/expires_after/") está em *6 minutos*. Em produção o /job/ deverá permanecer disponível por algo como *1 dia*.
