FROM rust:1.50 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install --path . --bin kv_server


FROM debian:buster-slim
RUN apt-get update && apt-get install -y curl libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/kv_server /usr/local/bin/kv_server
CMD ["kv_server"]
EXPOSE 8081
